dist: xenial
language: java
jdk: 
  - openjdk8

services:
  - docker

script:
  # Compile stuff
  - mvn -q -B -f pom.xml clean test jacoco:report coveralls:report
  - mvn -q -B -f samples/oshi/pom.xml clean install
  
  # Login to Docker Hub so that we can publish the sample docker image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
  - bash ./buildDockerImages.sh
